FROM node:24-alpine AS builder
WORKDIR /app
RUN apk add --no-cache openssl-dev openssl
COPY package*.json ./
COPY prisma-app ./
RUN npm ci
COPY . .
RUN npm run build
RUN rm -rf dist/api

FROM node:24-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma-app ./prisma-app
EXPOSE 3000
CMD ["npm", "run", "worker:prod"]